In [1]:
import numpy as np
import pandas as pd

from linearmodels import PooledOLS          # Pooled model
from linearmodels import RandomEffects      # Random-effect model
from linearmodels import PanelOLS           # Fixed-effect model
from linearmodels import FirstDifferenceOLS # First difference model

from linearmodels.panel import compare      # Compare the results of multiple models
from statsmodels.api import add_constant    # for matrices of regression design

In [2]:
df = pd.read_csv('Wages.csv')
df.head()

,exp,wks,bluecol,ind,south,smsa,married,sex,union,ed,black,lwage,id,time
0,3,32,no,0,yes,no,yes,male,no,9,no,5.56068,1,1
1,4,43,no,0,yes,no,yes,male,no,9,no,5.72031,1,2
2,5,40,no,0,yes,no,yes,male,no,9,no,5.99645,1,3
3,6,39,no,0,yes,no,yes,male,no,9,no,5.99645,1,4
4,7,42,no,1,yes,no,yes,male,no,9,no,6.06146,1,5

In [3]:
panel_df = df.set_index(['id', 'time'])
panel_df.head()

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no

           lwage
id time
1  1     5.56068
   2     5.72031
   3     5.99645
   4     5.99645
   5     6.06146

In [4]:
mod_pl = PooledOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa+married+union+bluecol', data=panel_df)
res_pl = mod_pl.fit()
res_pl.params.round(3)

Intercept         4.953
ed                0.058
exp               0.039
I(exp ** 2)      -0.001
wks               0.006
south[T.yes]     -0.078
smsa[T.yes]       0.131
married[T.yes]    0.293
union[T.yes]      0.099
bluecol[T.yes]   -0.130
Name: parameter, dtype: float64

In [5]:
mod_re = RandomEffects.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa', data=panel_df)
res_re = mod_re.fit()
res_re.params.round(3)

Intercept       3.890
ed              0.111
exp             0.088
I(exp ** 2)    -0.001
wks             0.001
south[T.yes]   -0.022
smsa[T.yes]    -0.037
Name: parameter, dtype: float64