In [1]:
import numpy as np
import pandas as pd

from linearmodels import PooledOLS          # Pooled model
from linearmodels import RandomEffects      # Random-effect model
from linearmodels import PanelOLS           # Fixed-effect model
from linearmodels import FirstDifferenceOLS # First difference model

from linearmodels.panel import compare      # Compare the results of multiple models
from statsmodels.api import add_constant    # for matrices of regression design

In [2]:
df = pd.read_csv('Wages.csv')
df.head()

,exp,wks,bluecol,ind,south,smsa,married,sex,union,ed,black,lwage,id,time
0,3,32,no,0,yes,no,yes,male,no,9,no,5.56068,1,1
1,4,43,no,0,yes,no,yes,male,no,9,no,5.72031,1,2
2,5,40,no,0,yes,no,yes,male,no,9,no,5.99645,1,3
3,6,39,no,0,yes,no,yes,male,no,9,no,5.99645,1,4
4,7,42,no,1,yes,no,yes,male,no,9,no,6.06146,1,5

In [3]:
panel_df = df.set_index(['id', 'time'])
panel_df.head()

         exp  wks bluecol  ind south smsa married   sex union  ed black  \
id time
1  1       3   32      no    0   yes   no     yes  male    no   9    no
   2       4   43      no    0   yes   no     yes  male    no   9    no
   3       5   40      no    0   yes   no     yes  male    no   9    no
   4       6   39      no    0   yes   no     yes  male    no   9    no
   5       7   42      no    1   yes   no     yes  male    no   9    no

           lwage
id time
1  1     5.56068
   2     5.72031
   3     5.99645
   4     5.99645
   5     6.06146

In [6]:
mod = PooledOLS.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa', data=panel_df)
res_ols = mod.fit()
res_ab = mod.fit(cov_type='clustered', cluster_entity=True)
res_dk = mod.fit(cov_type='kernel', kernel = "parzen")

compare({'OLS': res_ols, 'AB': res_ab, 'DK': res_dk}, stars=True, precision='std_errors')

                         Model Comparison
=================================================================
                                OLS           AB               DK
-----------------------------------------------------------------
Dep. Variable                 lwage        lwage            lwage
Estimator                 PooledOLS    PooledOLS        PooledOLS
No. Observations               4165         4165             4165
Cov. Est.                Unadjusted    Clustered   Driscoll-Kraay
R-squared                    0.3102       0.3102           0.3102
R-Squared (Within)           0.1758       0.1758           0.1758
R-Squared (Between)          0.3602       0.3602           0.3602
R-Squared (Overall)          0.3102       0.3102           0.3102
F-statistic                  311.60       311.60           311.60
P-value (F-stat)             0.0000       0.0000           0.0000
===================== ============= ============ ================
Intercept                 4.9551***    4.9551***        4.9551***
                           (0.0665)     (0.1334)         (0.0798)
ed                        0.0696***    0.0696***        0.0696***
                           (0.0022)     (0.0052)         (0.0025)
exp                       0.0447***    0.0447***        0.0447***
                           (0.0023)     (0.0052)         (0.0017)
I(exp ** 2)              -0.0007***   -0.0007***       -0.0007***
                        (5.185e-05)     (0.0001)      (1.549e-05)
wks                       0.0058***    0.0058***        0.0058***
                           (0.0012)     (0.0018)         (0.0015)
south[T.yes]             -0.1017***   -0.1017***       -0.1017***
                           (0.0133)     (0.0309)         (0.0024)
smsa[T.yes]               0.1185***    0.1185***        0.1185***
                           (0.0129)     (0.0274)         (0.0035)
-----------------------------------------------------------------

Std. Errors reported in parentheses
PanelModelComparison, id: 0x10b6fed0

In [7]:
mod_re = RandomEffects.from_formula(formula='lwage~1+ed+exp+I(exp**2)+wks+south+smsa', data=panel_df)
res_ols_re = mod_re.fit()
res_ab_re = mod_re.fit(cov_type='clustered', cluster_entity=True)
res_dk_re = mod_re.fit(cov_type='kernel', kernel = "parzen")

compare({'OLS': res_ols_re, 'AB': res_ab_re, 'DK': res_dk_re}, stars=True, precision='std_errors')

                           Model Comparison
======================================================================
                                  OLS              AB               DK
----------------------------------------------------------------------
Dep. Variable                   lwage           lwage            lwage
Estimator               RandomEffects   RandomEffects    RandomEffects
No. Observations                 4165            4165             4165
Cov. Est.                  Unadjusted       Clustered   Driscoll-Kraay
R-squared                      0.4129          0.4129           0.4129
R-Squared (Within)             0.5422          0.5422           0.5422
R-Squared (Between)           -1.0247         -1.0247          -1.0247
R-Squared (Overall)           -0.5996         -0.5996          -0.5996
F-statistic                    487.37          487.37           487.37
P-value (F-stat)               0.0000          0.0000           0.0000
===================== =============== =============== ================
Intercept                   3.8902***       3.8902***        3.8902***
                             (0.0938)        (0.1377)         (0.2015)
ed                          0.1113***       0.1113***        0.1113***
                             (0.0060)        (0.0084)         (0.0077)
exp                         0.0878***       0.0878***        0.0878***
                             (0.0028)        (0.0040)         (0.0284)
I(exp ** 2)                -0.0008***      -0.0008***          -0.0008
                           (6.25e-05)     (8.996e-05)         (0.0006)
wks                            0.0010          0.0010           0.0010
                             (0.0007)        (0.0009)         (0.0009)
south[T.yes]                  -0.0224         -0.0224        -0.0224**
                             (0.0279)        (0.0508)         (0.0090)
smsa[T.yes]                  -0.0375*         -0.0375        -0.0375**
                             (0.0202)        (0.0307)         (0.0174)
----------------------------------------------------------------------

Std. Errors reported in parentheses
PanelModelComparison, id: 0x11be83e0